# FRPM 指令测试dockerfile
# 首先拉去asp.net core 镜像 地址http://hub.docker.com
## docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1  
# dotnet3.1

# 将./app 目录下的文件都复制到/app, /app目录不存在则会自动创建
COPY ./app  /app

# 工作目录为/app

WORKDIR /app

ENTRYPOINT [ "dotnet","sample_app.dll" ]


