version: "3.7"
services: 
  redis:
    image:  redis:1.21
    ports: 
      - "3000"
      - "80:8080"
      - "9090-9091:8080-8081"
      - "6060:6060/udp"
    restart: on-failure/no/always/unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - oi_net
    links:
      - "db"
      - "db:database"